name: Node.js CI

# Trigger on pushes or pull‑requests to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - uses: actions/checkout@v3

      # 2. Install Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install deps
        run: npm install

      # 4. Run your tests
      - name: Run tests
        run: npm test
